### ISSUE TITLE
Aha! The Logo!

### ISSUE THREAD

**Issue by anuraghazra** [P-riyanka-prasad/P-riyanka-prasad#1]
Nice you've used the [github-readme-stats](https://github.com/anuraghazra/github-readme-stats)'s logo 😄 

but I'm not sure if it's a good idea. 
Because it's a project logo 🤔 not a user branding logo and I don't think it represent/indicates personal branding.

Maybe you could create your own branding logo 😉 that would be pretty nice I think. Or I could also help you create one!

**Comment by prykdev** [comment]
Oh thanks, I will do look into this for sure thanks once again 
plz help me in creating that i have no idea about that
